### ISSUE TITLE
No Alarm Integration Found

### ISSUE THREAD

**Issue by n00bster-za** [akasma74/Hass-Custom-Alarm#132]
I manually installed it and also tried installing it using HACS. I cannot see the Alarm integration at all 

there is no error in the logs. Cleared cache and tried other browsers.  

Please can someone help.

**Comment by akasma74** [comment]
That's because in newer versions of HA GUI part of this component doesn't work and is disabled as mentioned [here](https://github.com/akasma74/Hass-Custom-Alarm#important).
You can either use it with older version of HA or (if using any version of HA) use MQTT to control it (although it cannot be compared to GUI, I know).
