### ISSUE TITLE
No Pin Required in Lovelace 

### ISSUE THREAD

**Issue by bhyatyab** [akasma74/Hass-Custom-Alarm#92]
Issue:
There seems to be a bug with the lovelace alarm panel. 

No pin is required to disarm the alarm. 

Currently the lovelace alarm panel  disarms when using no pin or by entering the correct pin. 

The lovelace alarm  panel does not disarm using the incorrect pin.

The way the Lovelace alarm panel should work:
a pin should be required to disarm the alarm

My setup:
I'm running home assistance on a raspberry  pi.

This integration: v1.12.4

Home Assistant: v0.109.3

**Comment by akasma74** [comment]
Well, the thing is this component has more functionality than the standard alarm control panel.
That's why the best user experience you can get is provided by its own panel.
It's just "luck" that Lovelace alarm card works with it but I wouldn't recommend this combination unless you understand and happy with its limitations.

My plans are to migrate from the current panel to more Lovelace-friendly soluton (here's the [example](https://community.home-assistant.io/t/bwalarm-akasma74-edition/113666/712)) but it will take some time.
